spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
spring.datasource.username=testuser
spring.datasource.password=testpass


# consolemailsender\uD074\uB798\uC2A4\uC5D0\uC11C dev\uB97C \uBA54\uC77C \uC124\uC815\uC548\uD574\uC11C\ \uC5D0\uB7EC\uAC00\uB0AC\uB2E4(\uC704\uC5D0 \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC18C\uC2A4\uB9CC \uC788\uC744\uB54C)
# \uD558\uC9C0\uB9CC \uC544\uB798\uC5D0 \uBA54\uC77C\uC124\uC815\uC744 \uD574\uC90C\uC73C\uB85C\uC368 \uC2A4\uD504\uB9C1\uBD80\uD2B8\uAC00 \uC790\uB3D9\uC73C\uB85C \uBE48\uC744 \uB4F1\uB85D\uD574\uC90C
# \uADF8\uB7EC\uBA74 consolemailsender\uD074\uB798\uC2A4\uB294 \uC815\uC0C1\uB3D9\uC791\uD55C\uB2E4.
spring.mail.host=smtp.naver.com
spring.mail.port = 465

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.naver.com