spring.profiles.active=local

# \uAC1C\uBC1C\uD560 \uB54C\uC5D0\uB9CC create-drop \uB610\uB294 update\uB97C \uC0AC\uC6A9\uD558\uACE0 \uC6B4\uC601 \uD658\uACBD\uC5D0\uC11C\uB294 validate\uB97C \uC0AC\uC6A9\uD55C\uB2E4.
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.properties.hibernate.format_sql = true
logging.level.org.hibernate.SQL = DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


app.host=http://localhost:8080